[package]
name = "papeaks"
version = "0.1.0"
authors = ["futpib <futpib@gmail.com>"]

[dependencies]
libpulse-binding = { git = "https://github.com/futpib/pulse-binding-rust.git", branch = "issue-11-drop-failed-stream" }
arrayref = "0.3.5"
lazy_static = "1.2.0"
clap = "2.32.0"
